#!/usr/bin/env bash
# Daily runner — fetch latest GPU prices, regenerate report, commit + push.
# Designed to be invoked by a LaunchAgent or cron job.

set -euo pipefail

cd "$(dirname "$0")"
LOG_DATE=$(date +%Y-%m-%d)

echo "[$(date)] GPU Pricing daily run starting…"

python3 scripts/fetch.py
python3 scripts/report.py

# commit + push if there are changes
if [[ -n "$(git status --porcelain)" ]]; then
  git add data/observations.csv reports/ index.html
  git commit -m "daily snapshot ${LOG_DATE}" \
             -m "auto-generated by runner.sh"
  git push origin main
  echo "  → pushed to origin"
else
  echo "  → no changes to commit"
fi

echo "[$(date)] done."
